import About from '@/Components/About';
import Contact from '@/Components/Contact';
import Footer from '@/Components/Footer';
import Header from '@/Components/Header';
import Introduction from '@/Components/Introduction';
import Projects from '@/Components/Projects';
import AboutParallax from '@/Components/AboutParallax';
import Lenis from 'lenis';
import Head from 'next/head';
import { useEffect } from 'react';

export default function Home() {
    useEffect(() => {
        const lenis = new Lenis();

        function raf(time) {
            lenis.raf(time);
            requestAnimationFrame(raf);
        }

        requestAnimationFrame(raf);
    }, []);

    return (
        <>
            <Head>
                <title>HUBERT ŁEPSKI - DEV</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.png' />
            </Head>
            <>
                <Header />
                <Introduction />
                <AboutParallax />
                <About />
                <Projects />
                <Contact />
                <Footer />
            </>
        </>
    );
}
