import { useEffect } from 'react';
import About from '@/Components/About';
import Contact from '@/Components/Contact';
import Footer from '@/Components/Footer';
import Header from '@/Components/Header';
import Introduction from '@/Components/Introduction';
import Projects from '@/Components/Projects';
import AboutParallax from '@/Components/AboutParallax';
import Head from 'next/head';

import Lenis from 'lenis';
import LocomotiveScroll from 'locomotive-scroll';

export default function Home() {
    {
        /*  useEffect(() => {
        const lenis = new Lenis();

        function raf(time) {
            lenis.raf(time);
            requestAnimationFrame(raf);
        }

        requestAnimationFrame(raf);
    }, []); */
    }

    useEffect(() => {
        (async () => {
            const LocomotiveScroll = (await import('locomotive-scroll'))
                .default;

            const locomotiveScroll = new LocomotiveScroll();
        })();
    }, []);

    return (
        <>
            <Head>
                <title>HUBERT ŁEPSKI - DEV</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.png' />
            </Head>
            <>
                <Header />
                <Introduction />
                <article
                    className='bufferBeforeParallax'
                    style={{
                        height: '12.5vh',
                        zIndex: '2',
                        position: 'relative',
                        backgroundColor: '#000',
                    }}
                ></article>
                <AboutParallax />
                <article
                    className='bufferAfterParallax'
                    style={{
                        height: '10vh',
                        zIndex: '3',
                        position: 'relative',
                        backgroundColor: '#000',
                    }}
                ></article>
                <About />
                <Projects />
                <Contact />
                <Footer />
            </>
        </>
    );
}
